name: Build
'on':
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Move Pom.xml to Root
        run: mv .github/workflows/pom.xml ./pom.xml
      - name: Build and analyze
        env:
          GITHUB_TOKEN: >-
            a4b7d532-6289-40bf-8a2b-85df9eb312a0-322a13a9-00e8-478e-b575-dbd9d6caccfe
          SONAR_TOKEN: sqa_bca47d55147cb1b256a213a17c135dfe863be411
        run: >-
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=iamneo-production_a4b7d532-6289-40bf-8a2b-85df9eb312a0-322a13a9-00e8-478e-b575-dbd9d6caccfe
          -Dsonar.login=sqa_bca47d55147cb1b256a213a17c135dfe863be411
      - name: Trigger API
        if: always()
        env:
          API_URL: '${{ secrets.API_URL }}'
          API_SECRET: '${{ secrets.API_SECRET }}'
        run: >
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 2)

          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          API_PAYLOAD="{ \"repo_id\": \"$REPO_NAME\", \"branch_name\":
          \"$BRANCH_NAME\", \"api_secret\": \"$API_SECRET\" }"

          curl -X POST -H "Content-Type: application/json" -d "$API_PAYLOAD"
          $API_URL
